name="satyavardhan"
name.upper()
name.lower()
name.capitalize()
name.title()
name.swapcase()
name.strip()
name.lstrip()
name.rstrip()
name.replace("a", "o")
name.split()
name.join(["Hello", "World"])
name.startswith("s")
name.endswith("n")
name.find("v")
name.rfind("a")
name.count("a")
len(name)