name="satyavardhan"
print(name.upper(), "this is a test")
print(name.lower())
print(name.capitalize())
print(name.title())
print(name.swapcase())
print(name.strip()) 
print(name.lstrip())
print(name.rstrip())
print(name.replace("a", "o"))
print(name.split())
print(name.join(["Hello", "World"]))
print(name.startswith("s"))
print(name.endswith("n"))
print(name.find("v"))
print(name.rfind("a"))
print(name.count("a"))      

print(len(name))